### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Arpcoder** [feslima/HENSAD#2]
![image](https://github.com/feslima/HENSAD/assets/100352419/7525a535-36e1-4103-bec1-6201ab19b597)

@feslima I was going through this project and was trying to run it...I am getting this error after filling the stream table data...I have installed the application by extracting zipped files and simply running the application...Any help from your side will be appreciated...
Thanks and regards.

**Comment by feslima** [comment]
Hi @Arpcoder

Can you submit the contents of the log file here? It will be extremely helpful to debug this issue.

**Comment by Arpcoder** [comment]
@feslima Thanks a lot for responding and showing your concern.. But its working now.. I dont know how..

**Comment by feslima** [comment]
Good news then.

If anything happens again, don't hesitate to ping me through the repo issues.

Cheers,

**Comment by feslima** [comment]
I'm closing this issue for now.

**Comment by Arpcoder** [comment]
@feslima ..I am getting the same error again..I am attaching a recording and log file as you have requested before..Please have a look at it...Any kind of help will be appreciated..


[Video](https://www.loom.com/share/07b5dab92ba048c5951dd5221a6839f9)
[HENSAD.log](https://github.com/feslima/HENSAD/files/14640507/HENSAD.log)

Thanks and regards.
